# Generated by Django 3.2.7 on 2021-10-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='classe_niv',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
