# Generated by Django 3.2.7 on 2021-10-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_vote_classe_niv'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='niveau',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
