# Generated by Django 3.2.7 on 2021-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_asknewpassword_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.IntegerField(default=0),
        ),
    ]
