# Generated by Django 3.2.7 on 2021-10-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20211001_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='statue',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
